#!/bin/sh

case "$1" in
    start)
        echo "Starting aesd char driver module"
        /usr/bin/aesdchar_load
        ;;
    stop)
        echo "Stopping aesd char driver module"
        /usr/bin/aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac